perf/x86: Move events_sysfs_show outside CPU_SUP_INTEL
This patch moves events_sysfs_show outside CONFIG_CPU_SUP_INTEL,
because this interface will be also used on AMD power reporting
performance event.

Otherwise, below build error would be encountered:

All error/warnings (new ones prefixed by >>):

   In file included from include/linux/kobject.h:21:0,
                    from include/linux/module.h:17,
                    from arch/x86/kernel/cpu/perf_event_amd_power.c:13:
>> arch/x86/kernel/cpu/perf_event.h:663:31: error: 'events_sysfs_show' undeclared here (not in a function)
     .attr  = __ATTR(_name, 0444, events_sysfs_show, NULL), \
                                  ^
   include/linux/sysfs.h:103:10: note: in definition of macro '__ATTR'
     .show = _show,      \
             ^
>> arch/x86/kernel/cpu/perf_event_amd_power.c:244:1: note: in expansion of macro 'EVENT_ATTR_STR'
    EVENT_ATTR_STR(power-pkg, power_pkg, "event=0x01");
    ^

Reported-by: build test robot <lkp@intel.com>
Signed-off-by: Huang Rui <ray.huang@amd.com>